<a href="https://colab.research.google.com/github/jaredmccain-ux/pytorch-tutorial-learning-notes/blob/main/_downloads1/tensors_deeper_tutorial/tensors_deeper_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# For tips on running notebooks in Google Colab, see
# https://docs.pytorch.org/tutorials/beginner/colab
%matplotlib inline

[Introduction](introyt1_tutorial.html) \|\| **Tensors** \|\|
[Autograd](autogradyt_tutorial.html) \|\| [Building
Models](modelsyt_tutorial.html) \|\| [TensorBoard
Support](tensorboardyt_tutorial.html) \|\| [Training
Models](trainingyt.html) \|\| [Model Understanding](captumyt.html)

Introduction to PyTorch Tensors
===============================

Follow along with the video below or on
[youtube](https://www.youtube.com/watch?v=r7QDUPb2dCM).



In [1]:
# Run this cell to load the video
from IPython.display import display, HTML
html_code = """
<div style="margin-top:10px; margin-bottom:10px;">
  <iframe width="560" height="315" src="https://www.youtube.com/embed/r7QDUPb2dCM" frameborder="0" allow="accelerometer; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
</div>
"""
display(HTML(html_code))



Tensors are the central data abstraction in PyTorch. This interactive
notebook provides an in-depth introduction to the `torch.Tensor` class.

First things first, let's import the PyTorch module. We'll also add
Python's math module to facilitate some of the examples.


In [2]:
import torch
import math

Creating Tensors
================

The simplest way to create a tensor is with the `torch.empty()` call:


In [3]:
x = torch.empty(3, 4)
print(type(x))
print(x)

<class 'torch.Tensor'>
tensor([[-2.0387e-36,  4.4523e-41, -2.0387e-36,  4.4523e-41],
        [ 6.3376e-10,  2.1707e-18,  7.2128e+22,  2.1715e-18],
        [ 2.6552e-06,  1.0129e-11,  7.7195e-10,  1.0802e-05]])


Let's upack what we just did:

-   We created a tensor using one of the numerous factory methods
    attached to the `torch` module.
-   The tensor itself is 2-dimensional, having 3 rows and 4 columns.
-   The type of the object returned is `torch.Tensor`, which is an alias
    for `torch.FloatTensor`; by default, PyTorch tensors are populated
    with 32-bit floating point numbers. (More on data types below.)
-   You will probably see some random-looking values when printing your
    tensor. The `torch.empty()` call allocates memory for the tensor,
    but does not initialize it with any values - so what you're seeing
    is whatever was in memory at the time of allocation.

A brief note about tensors and their number of dimensions, and
terminology:

-   You will sometimes see a 1-dimensional tensor called a *vector.*
-   Likewise, a 2-dimensional tensor is often referred to as a *matrix.*
-   Anything with more than two dimensions is generally just called a
    tensor.

More often than not, you'll want to initialize your tensor with some
value. Common cases are all zeros, all ones, or random values, and the
`torch` module provides factory methods for all of these:


In [4]:
zeros = torch.zeros(2, 3)
print(zeros)

ones = torch.ones(2, 3)
print(ones)

torch.manual_seed(1729)
random = torch.rand(2, 3)
print(random)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])


The factory methods all do just what you'd expect - we have a tensor
full of zeros, another full of ones, and another with random values
between 0 and 1.

Random Tensors and Seeding
==========================

Speaking of the random tensor, did you notice the call to
`torch.manual_seed()` immediately preceding it? Initializing tensors,
such as a model's learning weights, with random values is common but
there are times - especially in research settings - where you'll want
some assurance of the reproducibility of your results. Manually setting
your random number generator's seed is the way to do this. Let's look
more closely:


In [5]:
torch.manual_seed(1729)
random1 = torch.rand(2, 3)
print(random1)

random2 = torch.rand(2, 3)
print(random2)

torch.manual_seed(1729)
random3 = torch.rand(2, 3)
print(random3)

random4 = torch.rand(2, 3)
print(random4)

tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])
tensor([[0.3126, 0.3791, 0.3087],
        [0.0736, 0.4216, 0.0691]])
tensor([[0.2332, 0.4047, 0.2162],
        [0.9927, 0.4128, 0.5938]])


What you should see above is that `random1` and `random3` carry
identical values, as do `random2` and `random4`. Manually setting the
RNG's seed resets it, so that identical computations depending on random
number should, in most settings, provide identical results.

For more information, see the [PyTorch documentation on
reproducibility](https://pytorch.org/docs/stable/notes/randomness.html).

Tensor Shapes
=============

Often, when you're performing operations on two or more tensors, they
will need to be of the same *shape* - that is, having the same number of
dimensions and the same number of cells in each dimension. For that, we
have the `torch.*_like()` methods:


In [6]:
x = torch.empty(2, 2, 3)
print(x.shape)
print(x)

empty_like_x = torch.empty_like(x)
print(empty_like_x.shape)
print(empty_like_x)

zeros_like_x = torch.zeros_like(x)
print(zeros_like_x.shape)
print(zeros_like_x)

ones_like_x = torch.ones_like(x)
print(ones_like_x.shape)
print(ones_like_x)

rand_like_x = torch.rand_like(x)
print(rand_like_x.shape)
print(rand_like_x)

torch.Size([2, 2, 3])
tensor([[[3.2915e-12, 0.0000e+00, 3.6352e-15],
         [0.0000e+00, 5.9230e+03, 4.4523e-41]],

        [[1.5835e-43, 0.0000e+00, 3.2591e-12],
         [0.0000e+00, 1.6198e-12, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[3.2910e-12, 0.0000e+00, 0.0000e+00],
         [1.5046e-36, 2.9922e-15, 0.0000e+00]],

        [[1.0842e-19, 0.0000e+00, 3.2591e-12],
         [0.0000e+00, 3.2590e-12, 0.0000e+00]]])
torch.Size([2, 2, 3])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])
torch.Size([2, 2, 3])
tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])
torch.Size([2, 2, 3])
tensor([[[0.6128, 0.1519, 0.0453],
         [0.5035, 0.9978, 0.3884]],

        [[0.6929, 0.1703, 0.1384],
         [0.4759, 0.7481, 0.0361]]])


The first new thing in the code cell above is the use of the `.shape`
property on a tensor. This property contains a list of the extent of
each dimension of a tensor - in our case, `x` is a three-dimensional
tensor with shape 2 x 2 x 3.

Below that, we call the `.empty_like()`, `.zeros_like()`,
`.ones_like()`, and `.rand_like()` methods. Using the `.shape` property,
we can verify that each of these methods returns a tensor of identical
dimensionality and extent.

The last way to create a tensor that will cover is to specify its data
directly from a PyTorch collection:


In [7]:
some_constants = torch.tensor([[3.1415926, 2.71828], [1.61803, 0.0072897]])
print(some_constants)

some_integers = torch.tensor((2, 3, 5, 7, 11, 13, 17, 19))
print(some_integers)

more_integers = torch.tensor(((2, 4, 6), [3, 6, 9]))
print(more_integers)

tensor([[3.1416, 2.7183],
        [1.6180, 0.0073]])
tensor([ 2,  3,  5,  7, 11, 13, 17, 19])
tensor([[2, 4, 6],
        [3, 6, 9]])


Using `torch.tensor()` is the most straightforward way to create a
tensor if you already have data in a Python tuple or list. As shown
above, nesting the collections will result in a multi-dimensional
tensor.

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p><code>torch.tensor()</code> creates a copy of the data.</p>

</div>

Tensor Data Types
=================

Setting the datatype of a tensor is possible a couple of ways:


In [8]:
a = torch.ones((2, 3), dtype=torch.int16)
print(a)

b = torch.rand((2, 3), dtype=torch.float64) * 20.
print(b)

c = b.to(torch.int32)
print(c)

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int16)
tensor([[ 0.9956,  1.4148,  5.8364],
        [11.2406, 11.2083, 11.6692]], dtype=torch.float64)
tensor([[ 0,  1,  5],
        [11, 11, 11]], dtype=torch.int32)


The simplest way to set the underlying data type of a tensor is with an
optional argument at creation time. In the first line of the cell above,
we set `dtype=torch.int16` for the tensor `a`. When we print `a`, we can
see that it's full of `1` rather than `1.` - Python's subtle cue that
this is an integer type rather than floating point.

Another thing to notice about printing `a` is that, unlike when we left
`dtype` as the default (32-bit floating point), printing the tensor also
specifies its `dtype`.

You may have also spotted that we went from specifying the tensor's
shape as a series of integer arguments, to grouping those arguments in a
tuple. This is not strictly necessary - PyTorch will take a series of
initial, unlabeled integer arguments as a tensor shape - but when adding
the optional arguments, it can make your intent more readable.

The other way to set the datatype is with the `.to()` method. In the
cell above, we create a random floating point tensor `b` in the usual
way. Following that, we create `c` by converting `b` to a 32-bit integer
with the `.to()` method. Note that `c` contains all the same values as
`b`, but truncated to integers.

For more information, see the [data types
documentation](https://pytorch.org/docs/stable/tensor_attributes.html#torch.dtype).

Math & Logic with PyTorch Tensors
=================================

Now that you know some of the ways to create a tensor... what can you do
with them?

Let's look at basic arithmetic first, and how tensors interact with
simple scalars:


In [9]:
ones = torch.zeros(2, 2) + 1
twos = torch.ones(2, 2) * 2
threes = (torch.ones(2, 2) * 7 - 1) / 2
fours = twos ** 2
sqrt2s = twos ** 0.5

print(ones)
print(twos)
print(threes)
print(fours)
print(sqrt2s)

tensor([[1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[4., 4.],
        [4., 4.]])
tensor([[1.4142, 1.4142],
        [1.4142, 1.4142]])


As you can see above, arithmetic operations between tensors and scalars,
such as addition, subtraction, multiplication, division, and
exponentiation are distributed over every element of the tensor. Because
the output of such an operation will be a tensor, you can chain them
together with the usual operator precedence rules, as in the line where
we create `threes`.

Similar operations between two tensors also behave like you'd
intuitively expect:


In [10]:
powers2 = twos ** torch.tensor([[1, 2], [3, 4]])
print(powers2)

fives = ones + fours
print(fives)

dozens = threes * fours
print(dozens)

tensor([[ 2.,  4.],
        [ 8., 16.]])
tensor([[5., 5.],
        [5., 5.]])
tensor([[12., 12.],
        [12., 12.]])


It's important to note here that all of the tensors in the previous code
cell were of identical shape. What happens when we try to perform a
binary operation on tensors if dissimilar shape?

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>The following cell throws a run-time error. This is intentional.<pre><code>a = torch.rand(2, 3)
b = torch.rand(3, 2)</p>
<p>print(a * b)</code></pre></p>

</div>



In the general case, you cannot operate on tensors of different shape
this way, even in a case like the cell above, where the tensors have an
identical number of elements.

In Brief: Tensor Broadcasting
=============================

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>If you are familiar with broadcasting semantics in NumPyndarrays, you’ll find the same rules apply here.</p>

</div>

The exception to the same-shapes rule is *tensor broadcasting.* Here's
an example:


In [11]:
rand = torch.rand(2, 4)
doubled = rand * (torch.ones(1, 4) * 2)

print(rand)
print(doubled)

tensor([[0.6146, 0.5999, 0.5013, 0.9397],
        [0.8656, 0.5207, 0.6865, 0.3614]])
tensor([[1.2291, 1.1998, 1.0026, 1.8793],
        [1.7312, 1.0413, 1.3730, 0.7228]])


What's the trick here? How is it we got to multiply a 2x4 tensor by a
1x4 tensor?

Broadcasting is a way to perform an operation between tensors that have
similarities in their shapes. In the example above, the one-row,
four-column tensor is multiplied by *both rows* of the two-row,
four-column tensor.

This is an important operation in Deep Learning. The common example is
multiplying a tensor of learning weights by a *batch* of input tensors,
applying the operation to each instance in the batch separately, and
returning a tensor of identical shape - just like our (2, 4) \* (1, 4)
example above returned a tensor of shape (2, 4).

The rules for broadcasting are:

-   Each tensor must have at least one dimension - no empty tensors.
-   Comparing the dimension sizes of the two tensors, *going from last
    to first:*
    -   Each dimension must be equal, *or*
    -   One of the dimensions must be of size 1, *or*
    -   The dimension does not exist in one of the tensors

Tensors of identical shape, of course, are trivially "broadcastable", as
you saw earlier.

Here are some examples of situations that honor the above rules and
allow broadcasting:


In [13]:
a =     torch.ones(4, 3, 2)

print(a)
print(torch.rand( 3,2) )
b = a * torch.rand(   3, 2) # 3rd & 2nd dims identical to a, dim 1 absent
print(b)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[0.6493, 0.2633],
        [0.4762, 0.0548],
        [0.2024, 0.5731]])
tensor([[[0.7191, 0.4067],
         [0.7301, 0.6276],
         [0.7357, 0.0381]],

        [[0.7191, 0.4067],
         [0.7301, 0.6276],
         [0.7357, 0.0381]],

        [[0.7191, 0.4067],
         [0.7301, 0.6276],
         [0.7357, 0.0381]],

        [[0.7191, 0.4067],
         [0.7301, 0.6276],
         [0.7357, 0.0381]]])
tensor([[[0.2138, 0.2138],
         [0.5395, 0.5395],
         [0.3686, 0.3686]],

        [[0.2138, 0.2138],
         [0.5395, 0.5395],
         [0.3686, 0.3686]],

        [[0.2138, 0.2138],
         [0.5395, 0.5395],
         [0.3686, 0.3686]],

        [[0.2138, 0.2138],
         [0.5395, 0.5395],
         [0.3686, 0.3686]]])
tensor([[[0.4007, 0.7

Look closely at the values of each tensor above:

-   The multiplication operation that created `b` was broadcast over
    every "layer" of `a`.
-   For `c`, the operation was broadcast over every layer and row of
    `a` - every 3-element column is identical.
-   For `d`, we switched it around - now every *row* is identical,
    across layers and columns.

For more information on broadcasting, see the [PyTorch
documentation](https://pytorch.org/docs/stable/notes/broadcasting.html)
on the topic.

Here are some examples of attempts at broadcasting that will fail:

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>The following cell throws a run-time error. This is intentional.<pre><code>a =     torch.ones(4, 3, 2)</p>
<p>b = a * torch.rand(4, 3)    # dimensions must match last-to-first</p>
<p>c = a * torch.rand(   2, 3) # both 3rd &amp; 2nd dims different</p>
<p>d = a * torch.rand((0, ))   # can&#x27;t broadcast with an empty tensor</code></pre></p>

</div>



More Math with Tensors
======================

PyTorch tensors have over three hundred operations that can be performed
on them.

Here is a small sample from some of the major categories of operations:

**解释clamp函数**
简单来说，`torch.clamp(a, -0.5, 0.5)` 的作用是**将张量 `a` 中的每一个元素“限制”在  的范围内**。

如果把张量里的数值想象成身高，这个函数就像是一个**带有天花板和地板的房间**：太高的会被压低，太矮的会被拉高，中间的则保持不变。

---

### 具体逻辑

对于张量 `a` 中的任意一个元素 ：

* 如果 ，它会被强制改为 ****。
* 如果 ，它会被强制改为 ****。
* 如果 ，它**保持原样**。

数学表达公式为：


---

### 代码示例

让我们看一个直观的例子：

```python
import torch

a = torch.tensor([1.2, 0.2, -0.1, -0.8, 0.5])
output = torch.clamp(a, -0.5, 0.5)

print(output)
# 输出结果: tensor([ 0.5000,  0.2000, -0.1000, -0.5000,  0.5000])

```

* **1.2** 超过了 0.5  变成 **0.5**
* **0.2** 在范围内  保持 **0.2**
* **-0.8** 低于了 -0.5  变成 **-0.5**

---

### 常见的应用场景

1. **防止梯度爆炸**：在深度学习训练中，如果某个梯度的值变得极端大，可以用 `clamp` 把它强行拉回合理的范围。
2. **图像处理**：图像的像素值通常在  或  之间。在进行一些图像增强操作（比如加噪、亮度调整）后，数值可能会超出范围，此时用 `clamp(0, 1)` 可以确保图片格式依然合法。
3. **数值稳定性**：在计算类似  时，为了防止  变成  导致结果变成负无穷，可以先用 `torch.clamp(x, min=1e-7)` 给它设个“底线”。


# **解释 vector and linear algebra operations这几行中print里的函数代表什么意思：**

这几行代码涉及的是线性代数（Linear Algebra）中最核心的几个运算：**向量积**、**矩阵乘法**和**奇异值分解**。

我们来逐一拆解这些函数的输出含义：

---

### 1. `torch.linalg.cross(v2, v1)`：向量外积（叉乘）

* **数学含义**：计算两个三维向量的叉乘。结果是一个**垂直于 `v2` 和 `v1` 所构成的平面**的新向量。
* **输出含义**：
* 它返回的是一个向量。
* **方向**：遵循右手法则。
* **大小**：等于这两个向量组成的平行四边形的面积。


* **代码注释解释**：`v1 x v2 == -v2 x v1` 提醒你叉乘是**反交换**的。如果你调换顺序，结果向量的方向会完全相反（正负号翻转）。

---

### 2. `torch.linalg.matmul(m1, m2)`：矩阵乘法

* **数学含义**：标准的矩阵乘积（Matrix Multiplication）。
* **输出含义**：
* 如果 `m1` 是  矩阵，`m2` 是  矩阵，结果 `m3` 就是  矩阵。
* **注释里的 `3 times m1**`：这通常意味着在这个特定的例子里，`m2` 可能是一个单位矩阵的 3 倍（即 ），所以效果等同于把 `m1` 里的每个元素都乘以 3。



---

### 3. `torch.linalg.svd(m3)`：奇异值分解 (SVD)

这是线性代数中最强大的工具之一，它将矩阵 `m3` 分解为三个部分。

* **输出内容**：该函数会返回一个包含三个张量的**元组 (Tuple)**：
1. **`U` (左奇异向量)**：正交矩阵，代表空间旋转。
2. **`S` (奇异值)**：一个一维向量。这些值按**降序**排列，代表了矩阵在各个方向上的“强度”或“权重”。（如果某些值接近 0，说明矩阵在该维度上坍缩了）。
3. **`Vh` (右奇异向量的转置)**：也是正交矩阵。






In [17]:
# common functions
a = torch.rand(2, 4) * 2 - 1
print('Common functions:')
print(torch.abs(a))
print(torch.ceil(a))
print(torch.floor(a))
print(torch.clamp(a, -0.5, 0.5))

# trigonometric functions and their inverses
angles = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
sines = torch.sin(angles)
inverses = torch.asin(sines)
print('\nSine and arcsine:')
print(angles)
print(sines)
print(inverses)

# bitwise operations
print('\nBitwise XOR:')
b = torch.tensor([1, 5, 11])
c = torch.tensor([2, 7, 10])
print(torch.bitwise_xor(b, c))

# comparisons:
print('\nBroadcasted, element-wise equality comparison:')
d = torch.tensor([[1., 2.], [3., 4.]])
e = torch.ones(1, 2)  # many comparison ops support broadcasting!
print(torch.eq(d, e)) # returns a tensor of type bool

# reductions:
print('\nReduction ops:')
print(torch.max(d))        # returns a single-element tensor
print(torch.max(d).item()) # extracts the value from the returned tensor
print(torch.mean(d))       # average
print(torch.std(d))        # standard deviation
print(torch.prod(d))       # product of all numbers 所有数字的乘积
print(torch.unique(torch.tensor([1, 2, 1, 2, 1, 2]))) # filter unique elements

# vector and linear algebra operations
print("\nvector and linear algebra operations")
v1 = torch.tensor([1., 0., 0.])         # x unit vector
v2 = torch.tensor([0., 1., 0.])         # y unit vector
m1 = torch.rand(2, 2)                   # random matrix
m2 = torch.tensor([[3., 0.], [0., 3.]]) # three times identity matrix
print(v1)
print(v2)
print(m1)
print(m2)

print('\nVectors & Matrices:')
print(torch.linalg.cross(v2, v1)) # negative of z unit vector (v1 x v2 == -v2 x v1)
print(m1)
m3 = torch.linalg.matmul(m1, m2)
print(m3)                  # 3 times m1
print(torch.linalg.svd(m3))       # singular value decomposition

Common functions:
tensor([[0.0365, 0.9614, 0.3090, 0.1713],
        [0.8608, 0.0704, 0.1018, 0.2531]])
tensor([[1., 1., 1., -0.],
        [-0., -0., -0., 1.]])
tensor([[ 0.,  0.,  0., -1.],
        [-1., -1., -1.,  0.]])
tensor([[ 0.0365,  0.5000,  0.3090, -0.1713],
        [-0.5000, -0.0704, -0.1018,  0.2531]])

Sine and arcsine:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 0.7854])

Bitwise XOR:
tensor([3, 2, 1])

Broadcasted, element-wise equality comparison:
tensor([[ True, False],
        [False, False]])

Reduction ops:
tensor(4.)
4.0
tensor(2.5000)
tensor(1.2910)
tensor(24.)
tensor([1, 2])

vector and linear algebra operations
tensor([1., 0., 0.])
tensor([0., 1., 0.])
tensor([[0.9411, 0.4922],
        [0.5461, 0.5396]])
tensor([[3., 0.],
        [0., 3.]])

Vectors & Matrices:
tensor([ 0.,  0., -1.])
tensor([[0.9411, 0.4922],
        [0.5461, 0.5396]])
tensor([[2.8234, 1.4766],
        [1.6382, 1.6188]])
torch.

This is a small sample of operations. For more details and the full
inventory of math functions, have a look at the
[documentation](https://pytorch.org/docs/stable/torch.html#math-operations).
For more details and the full inventory of linear algebra operations,
have a look at this
[documentation](https://pytorch.org/docs/stable/linalg.html).

Altering Tensors in Place
=========================

Most binary operations on tensors will return a third, new tensor. When
we say `c = a * b` (where `a` and `b` are tensors), the new tensor `c`
will occupy a region of memory distinct from the other tensors.

There are times, though, that you may wish to alter a tensor in place
-for example, if you're doing an element-wise computation where you can
discard intermediate values. For this, most of the math functions have a
version with an appended underscore (`_`) that will alter a tensor in
place.

For example:


In [18]:
a = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('a:')
print(a)
print(torch.sin(a))   # this operation creates a new tensor in memory
print(a)              # a has not changed

b = torch.tensor([0, math.pi / 4, math.pi / 2, 3 * math.pi / 4])
print('\nb:')
print(b)
print(torch.sin_(b))  # note the underscore
print(b)              # b has changed

a:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7854, 1.5708, 2.3562])

b:
tensor([0.0000, 0.7854, 1.5708, 2.3562])
tensor([0.0000, 0.7071, 1.0000, 0.7071])
tensor([0.0000, 0.7071, 1.0000, 0.7071])


For arithmetic operations, there are functions that behave similarly:


In [19]:
a = torch.ones(2, 2)
b = torch.rand(2, 2)

print('Before:')
print(a)
print(b)
print('\nAfter adding:')
print(a.add_(b))
print(a)
print(b)
print('\nAfter multiplying')
print(b.mul_(b))
print(b)

Before:
tensor([[1., 1.],
        [1., 1.]])
tensor([[0.3053, 0.1973],
        [0.3285, 0.5655]])

After adding:
tensor([[1.3053, 1.1973],
        [1.3285, 1.5655]])
tensor([[1.3053, 1.1973],
        [1.3285, 1.5655]])
tensor([[0.3053, 0.1973],
        [0.3285, 0.5655]])

After multiplying
tensor([[0.0932, 0.0389],
        [0.1079, 0.3198]])
tensor([[0.0932, 0.0389],
        [0.1079, 0.3198]])


Note that these in-place arithmetic functions are methods on the
`torch.Tensor` object, not attached to the `torch` module like many
other functions (e.g., `torch.sin()`). As you can see from `a.add_(b)`,
*the calling tensor is the one that gets changed in place.*

There is another option for placing the result of a computation in an
existing, allocated tensor. Many of the methods and functions we've seen
so far - including creation methods! - have an `out` argument that lets
you specify a tensor to receive the output. If the `out` tensor is the
correct shape and `dtype`, this can happen without a new memory
allocation:


In [20]:
a = torch.rand(2, 2)
b = torch.rand(2, 2)
c = torch.zeros(2, 2)
old_id = id(c)

print(c)
d = torch.matmul(a, b, out=c)
print(c)                # contents of c have changed

assert c is d           # test c & d are same object, not just containing equal values
assert id(c) == old_id  # make sure that our new c is the same object as the old one

torch.rand(2, 2, out=c) # works for creation too!
print(c)                # c has changed again
assert id(c) == old_id  # still the same object!

tensor([[0., 0.],
        [0., 0.]])
tensor([[0.3508, 0.7274],
        [0.5542, 0.9844]])
tensor([[0.6293, 0.6264],
        [0.4704, 0.6077]])


# **解释assert的用法：**

在 PyTorch（以及整个 Python 编程）中，`assert`（断言）是一个**调试工具**。它的核心逻辑是：**“我断定这里的条件一定是真的，如果不是，程序立刻报错停下来。”**

它的基本语法是：
`assert 条件, "错误提示信息"`

---

### 1. 为什么在 PyTorch 里经常看到它？

在处理张量（Tensor）时，形状（Shape）不匹配是报错的头号原因。开发者通常用 `assert` 来确保张量的维度是正确的，防止程序带着错误的数据继续往下运行，导致后面出现更难调试的 Bug。

#### 常见用法示例：

```python
import torch

def model_forward(input_tensor):
    # 我断定输入的张量第一维（batch_size）必须是 16
    # 如果不是 16，程序直接在这里崩溃，并打印出提示
    assert input_tensor.shape[0] == 16, f"Batch size 期待 16，但实际收到 {input_tensor.shape[0]}"
    
    # 逻辑代码...
    return input_tensor * 2

x = torch.randn(8, 3)  # 这里故意传了一个 batch_size 为 8 的
model_forward(x)

```

**运行结果：**
`AssertionError: Batch size 期待 16，但实际收到 8`

---

### 2. `assert` 的三大使用场景

* **检查维度对齐：** 在做矩阵乘法（`matmul`）之前，确认维度  的列数等于维度  的行数。
* **检查设备一致性：** 确认两个张量都在同一个设备上（都在 GPU 上，或者都在 CPU 上），因为跨设备计算会报错。
* `assert a.device == b.device, "两个张量不在同一个设备上！"`


* **检查数值合法性：** 比如某个概率值必须在  到  之间。
* `assert torch.all(probs >= 0) and torch.all(probs <= 1)`



---

### 3. 注意事项（重要！）

1. **它不是用来处理业务逻辑的：** `assert` 应该只用于捕捉那些“理论上不该发生”的程序错误。如果是用户输入错误，应该使用 `if...raise ValueError`。
2. **可以被禁用：** 在运行 Python 时如果使用了 `-O`（优化模式）标志，所有的 `assert` 语句会被自动忽略。所以，**千万不要把程序运行必不可少的逻辑写在 `assert` 里**。

---

### 总结

`assert` 就像是代码里的**安检站**。它在开发阶段帮你守住底线，确保张量的形状、设备、数值完全符合你的预期。

**你是在读别人的模型源码时看到了很多 `assert` 吗？如果是的话，那些通常是作者为了告诉你：“喂，这个模型只支持这种尺寸的输入！”**

Copying Tensors
===============

As with any object in Python, assigning a tensor to a variable makes the
variable a *label* of the tensor, and does not copy it. For example:


In [21]:
a = torch.ones(2, 2)
b = a

a[0][1] = 561  # we change a...
print(b)       # ...and b is also altered

tensor([[  1., 561.],
        [  1.,   1.]])


But what if you want a separate copy of the data to work on? The
`clone()` method is there for you:


In [22]:
a = torch.ones(2, 2)
b = a.clone()

assert b is not a      # different objects in memory...
print(torch.eq(a, b))  # ...but still with the same contents!

a[0][1] = 561          # a changes...
print(b)               # ...but b is still all ones

tensor([[True, True],
        [True, True]])
tensor([[1., 1.],
        [1., 1.]])


**There is an important thing to be aware of when using
\`\`clone()\`\`.** If your source tensor has autograd, enabled then so
will the clone. **This will be covered more deeply in the video on
autograd,** but if you want the light version of the details, continue
on.

*In many cases, this will be what you want.* For example, if your model
has multiple computation paths in its `forward()` method, and *both* the
original tensor and its clone contribute to the model's output, then to
enable model learning you want autograd turned on for both tensors. If
your source tensor has autograd enabled (which it generally will if it's
a set of learning weights or derived from a computation involving the
weights), then you'll get the result you want.

On the other hand, if you're doing a computation where *neither* the
original tensor nor its clone need to track gradients, then as long as
the source tensor has autograd turned off, you're good to go.

*There is a third case,* though: Imagine you're performing a computation
in your model's `forward()` function, where gradients are turned on for
everything by default, but you want to pull out some values mid-stream
to generate some metrics. In this case, you *don't* want the cloned copy
of your source tensor to track gradients - performance is improved with
autograd's history tracking turned off. For this, you can use the
`.detach()` method on the source tensor:


In [23]:
a = torch.rand(2, 2, requires_grad=True) # turn on autograd
print(a)

b = a.clone()
print(b)

c = a.detach().clone()
print(c)

print(a)

tensor([[0.4757, 0.5874],
        [0.4363, 0.6339]], requires_grad=True)
tensor([[0.4757, 0.5874],
        [0.4363, 0.6339]], grad_fn=<CloneBackward0>)
tensor([[0.4757, 0.5874],
        [0.4363, 0.6339]])
tensor([[0.4757, 0.5874],
        [0.4363, 0.6339]], requires_grad=True)


What's happening here?

-   We create `a` with `requires_grad=True` turned on. **We haven't
    covered this optional argument yet, but will during the unit on
    autograd.**
-   When we print `a`, it informs us that the property
    `requires_grad=True` - this means that autograd and computation
    history tracking are turned on.
-   We clone `a` and label it `b`. When we print `b`, we can see that
    it's tracking its computation history - it has inherited `a`'s
    autograd settings, and added to the computation history.
-   We clone `a` into `c`, but we call `detach()` first.
-   Printing `c`, we see no computation history, and no
    `requires_grad=True`.

The `detach()` method *detaches the tensor from its computation
history.* It says, "do whatever comes next as if autograd was off." It
does this *without* changing `a` - you can see that when we print `a`
again at the end, it retains its `requires_grad=True` property.

Moving to
[Accelerator](https://pytorch.org/docs/stable/torch.html#accelerators)
\-\-\-\-\-\-\-\-\-\-\-\--

One of the major advantages of PyTorch is its robust acceleration on an
[accelerator](https://pytorch.org/docs/stable/torch.html#accelerators)
such as CUDA, MPS, MTIA, or XPU. So far, everything we've done has been
on CPU. How do we move to the faster hardware?

First, we should check whether an accelerator is available, with the
`is_available()` method.

<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>If you do not have an accelerator, the executable cells in this section will not execute anyaccelerator-related code.</p>

</div>



In [24]:
if torch.accelerator.is_available():
    print('We have an accelerator!')
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


Once we've determined that one or more accelerators is available, we
need to put our data someplace where the accelerator can see it. Your
CPU does computation on data in your computer's RAM. Your accelerator
has dedicated memory attached to it. Whenever you want to perform a
computation on a device, you must move *all* the data needed for that
computation to memory accessible by that device. (Colloquially, "moving
the data to memory accessible by the GPU" is shorted to, "moving the
data to the GPU".)

There are multiple ways to get your data onto your target device. You
may do it at creation time:


In [25]:
if torch.accelerator.is_available():
    gpu_rand = torch.rand(2, 2, device=torch.accelerator.current_accelerator())
    print(gpu_rand)
else:
    print('Sorry, CPU only.')

Sorry, CPU only.


By default, new tensors are created on the CPU, so we have to specify
when we want to create our tensor on the accelerator with the optional
`device` argument. You can see when we print the new tensor, PyTorch
informs us which device it's on (if it's not on CPU).

You can query the number of accelerators with
`torch.accelerator.device_count()`. If you have more than one
accelerator, you can specify them by index, take CUDA for example:
`device='cuda:0'`, `device='cuda:1'`, etc.

As a coding practice, specifying our devices everywhere with string
constants is pretty fragile. In an ideal world, your code would perform
robustly whether you're on CPU or accelerator hardware. You can do this
by creating a device handle that can be passed to your tensors instead
of a string:


In [26]:
my_device = torch.accelerator.current_accelerator() if torch.accelerator.is_available() else torch.device('cpu')
print('Device: {}'.format(my_device))

x = torch.rand(2, 2, device=my_device)
print(x)

Device: cpu
tensor([[0.3208, 0.4323],
        [0.1811, 0.6962]])


If you have an existing tensor living on one device, you can move it to
another with the `to()` method. The following line of code creates a
tensor on CPU, and moves it to whichever device handle you acquired in
the previous cell.


In [27]:
y = torch.rand(2, 2)
y = y.to(my_device)

It is important to know that in order to do computation involving two or
more tensors, *all of the tensors must be on the same device*. The
following code will throw a runtime error, regardless of whether you
have an accelerator device available, take CUDA for example:

``` {.python}
x = torch.rand(2, 2)
y = torch.rand(2, 2, device='cuda')
z = x + y  # exception will be thrown
```


Manipulating Tensor Shapes
==========================

Sometimes, you'll need to change the shape of your tensor. Below, we'll
look at a few common cases, and how to handle them.

Changing the Number of Dimensions
---------------------------------

One case where you might need to change the number of dimensions is
passing a single instance of input to your model. PyTorch models
generally expect *batches* of input.

For example, imagine having a model that works on 3 x 226 x 226 images
-a 226-pixel square with 3 color channels. When you load and transform
it, you'll get a tensor of shape `(3, 226, 226)`. Your model, though, is
expecting input of shape `(N, 3, 226, 226)`, where `N` is the number of
images in the batch. So how do you make a batch of one?


In [30]:
a = torch.rand(3, 226, 226)
b = a.unsqueeze(0)
c = b.unsqueeze(0)
print(a.shape)
print(b.shape)
print(c.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])
torch.Size([1, 1, 3, 226, 226])


The `unsqueeze()` method adds a dimension of extent 1. `unsqueeze(0)`
adds it as a new zeroth dimension - now you have a batch of one!

So if that's *un*squeezing? What do we mean by squeezing? We're taking
advantage of the fact that any dimension of extent 1 *does not* change
the number of elements in the tensor.


In [29]:
c = torch.rand(1, 1, 1, 1, 1)
print(c)

tensor([[[[[0.3118]]]]])


Continuing the example above, let's say the model's output is a
20-element vector for each input. You would then expect the output to
have shape `(N, 20)`, where `N` is the number of instances in the input
batch. That means that for our single-input batch, we'll get an output
of shape `(1, 20)`.

What if you want to do some *non-batched* computation with that output
-something that's just expecting a 20-element vector?


In [31]:
a = torch.rand(1, 20)
print(a.shape)
print(a)

b = a.squeeze(0)
print(b.shape)
print(b)

c = torch.rand(2, 2)
print(c.shape)

d = c.squeeze(0)
print(d.shape)

torch.Size([1, 20])
tensor([[0.8309, 0.1920, 0.8821, 0.3874, 0.6783, 0.9087, 0.0928, 0.7708, 0.6992,
         0.1549, 0.3806, 0.2857, 0.7246, 0.2635, 0.0255, 0.2897, 0.2722, 0.6472,
         0.9879, 0.9724]])
torch.Size([20])
tensor([0.8309, 0.1920, 0.8821, 0.3874, 0.6783, 0.9087, 0.0928, 0.7708, 0.6992,
        0.1549, 0.3806, 0.2857, 0.7246, 0.2635, 0.0255, 0.2897, 0.2722, 0.6472,
        0.9879, 0.9724])
torch.Size([2, 2])
torch.Size([2, 2])


You can see from the shapes that our 2-dimensional tensor is now
1-dimensional, and if you look closely at the output of the cell above
you'll see that printing `a` shows an "extra" set of square brackets
`[]` due to having an extra dimension.

You may only `squeeze()` dimensions of extent 1. See above where we try
to squeeze a dimension of size 2 in `c`, and get back the same shape we
started with. Calls to `squeeze()` and `unsqueeze()` can only act on
dimensions of extent 1 because to do otherwise would change the number
of elements in the tensor.

Another place you might use `unsqueeze()` is to ease broadcasting.
Recall the example above where we had the following code:

``` {.python}
a = torch.ones(4, 3, 2)

c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)
```

The net effect of that was to broadcast the operation over dimensions 0
and 2, causing the random, 3 x 1 tensor to be multiplied element-wise by
every 3-element column in `a`.

What if the random vector had just been 3-element vector? We'd lose the
ability to do the broadcast, because the final dimensions would not
match up according to the broadcasting rules. `unsqueeze()` comes to the
rescue:


In [32]:
a = torch.ones(4, 3, 2)
b = torch.rand(   3)     # trying to multiply a * b will give a runtime error
c = b.unsqueeze(1)       # change to a 2-dimensional tensor, adding new dim at the end
print(c.shape)
print(a * c)             # broadcasting works again!

torch.Size([3, 1])
tensor([[[0.3872, 0.3872],
         [0.2341, 0.2341],
         [0.6677, 0.6677]],

        [[0.3872, 0.3872],
         [0.2341, 0.2341],
         [0.6677, 0.6677]],

        [[0.3872, 0.3872],
         [0.2341, 0.2341],
         [0.6677, 0.6677]],

        [[0.3872, 0.3872],
         [0.2341, 0.2341],
         [0.6677, 0.6677]]])


The `squeeze()` and `unsqueeze()` methods also have in-place versions,
`squeeze_()` and `unsqueeze_()`:


In [33]:
batch_me = torch.rand(3, 226, 226)
print(batch_me.shape)
batch_me.unsqueeze_(0)
print(batch_me.shape)

torch.Size([3, 226, 226])
torch.Size([1, 3, 226, 226])


Sometimes you'll want to change the shape of a tensor more radically,
while still preserving the number of elements and their contents. One
case where this happens is at the interface between a convolutional
layer of a model and a linear layer of the model - this is common in
image classification models. A convolution kernel will yield an output
tensor of shape *features x width x height,* but the following linear
layer expects a 1-dimensional input. `reshape()` will do this for you,
provided that the dimensions you request yield the same number of
elements as the input tensor has:


In [34]:
output3d = torch.rand(6, 20, 20)
print(output3d.shape)

input1d = output3d.reshape(6 * 20 * 20)
print(input1d.shape)

# can also call it as a method on the torch module:
print(torch.reshape(output3d, (6 * 20 * 20,)).shape)

torch.Size([6, 20, 20])
torch.Size([2400])
torch.Size([2400])


<div style="background-color: #54c7ec; color: #fff; font-weight: 700; padding-left: 10px; padding-top: 5px; padding-bottom: 5px"><strong>NOTE:</strong></div>

<div style="background-color: #f3f4f7; padding-left: 10px; padding-top: 10px; padding-bottom: 10px; padding-right: 10px">

<p>The <code>(6 * 20 * 20,)</code> argument in the final line of the cellabove is because PyTorch expects a  when specifying atensor shape - but when the shape is the first argument of a method, itlets us cheat and just use a series of integers. Here, we had to add theparentheses and comma to convince the method that this is really aone-element tuple.</p>

</div>

**When it can, `reshape()` will return a *view* on the tensor to be
changed - that is, a separate tensor object looking at the same
underlying region of memory. *This is important:* That means any change
made to the source tensor will be reflected in the view on that tensor,
unless you `clone()` it.**

There *are* conditions, beyond the scope of this introduction, where
`reshape()` has to return a tensor carrying a copy of the data. For more
information, see the
[docs](https://pytorch.org/docs/stable/torch.html#torch.reshape).


NumPy Bridge
============

In the section above on broadcasting, it was mentioned that PyTorch's
broadcast semantics are compatible with NumPy's - but the kinship
between PyTorch and NumPy goes even deeper than that.

If you have existing ML or scientific code with data stored in NumPy
ndarrays, you may wish to express that same data as PyTorch tensors,
whether to take advantage of PyTorch's GPU acceleration, or its
efficient abstractions for building ML models. It's easy to switch
between ndarrays and PyTorch tensors:


In [35]:
import numpy as np

numpy_array = np.ones((2, 3))
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1. 1. 1.]
 [1. 1. 1.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


PyTorch creates a tensor of the same shape and containing the same data
as the NumPy array, going so far as to keep NumPy's default 64-bit float
data type.

The conversion can just as easily go the other way:


In [36]:
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.2252, 0.3100, 0.4079],
        [0.2421, 0.3773, 0.2785]])
[[0.22523189 0.30998814 0.40786397]
 [0.24210405 0.3772729  0.2784776 ]]


It is important to know that these converted objects are using *the same
underlying memory* as their source objects, meaning that changes to one
are reflected in the other:


In [37]:
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.22523189  0.30998814  0.40786397]
 [ 0.24210405 17.          0.2784776 ]]
